---
# file: tasks/config_nsca.yml

- name: Configure NSCA
  template: src={{ ansible_distribution_release }}/nsca.cfg.j2
        dest={{ nsca_config_file }}
        owner=root group=root mode=0644
        backup=yes
  notify: Reload NSCA

- name: Ensure nsca is started and enabled
  service:
    name: "{{ nsca_service }}"
    state: started
    enabled: yes
