---
# file: tasks/config_nsca.yml

- name: Configure NSCA
  template:
    src: "{{ ansible_os_family }}/nsca.cfg.j2"
    dest: "{{ nsca_config_file }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    backup: yes
  notify: Reload NSCA

- name: Ensure nsca is started and enabled
  service:
    name: "{{ nsca_service }}"
    state: started
    enabled: yes
