---
# file: tasks/main.yml

- import_tasks: multi_os.yml
  tags:
    - config_nagios
    - nagios_server_main_config

- name: include epel on Centos/RedHat
  include_role:
    name: geerlingguy.repo-epel
  when: ansible_distribution == 'RedHat'

- name: Register var with stat nagios config file
  stat: path="{{ nagios_config_file }}"
  register: nagiosconfigfile

- name: main | update apt cache for ubuntu
  apt: update_cache=yes
  retries: 2
  delay: 2
  when: ansible_distribution == 'Ubuntu' and not nagiosconfigfile.stat.exists

# Installs packages in any platform and adds environment DEBIAN_FRONTEND for debian based os.
# DEBIAN_FRONTEND helps on ensuring not interactive in this case.
- name: main | install packages
  package: name={{ nagios_packages| join(',') }} state=present
  retries: 2
  delay: 2
  environment:
    DEBIAN_FRONTEND: noninteractive

- import_tasks: config_main_nagios.yml

# For generic operation
- import_tasks: config_nagios.yml
  tags:
    - config_nagios

- import_tasks: config_nsca.yml

- import_tasks: nagios_cron.yml
  tags:
    - config_nagios_cron

- import_tasks: config_notifications.yml
